# Generated by Django 5.1.7 on 2025-04-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_alter_appointment_options_remove_doctor_category_and_more'),
    ]

    operations = [
    ]
